FROM gitpod/workspace-full:latest

USER root

RUN apt-get update \
    && apt-get install -yq git g++ gcc make automake libtool bison flex telnet db-util bzip2 \
    && apt-get install -yq libcrypto++-dev libjsoncpp-dev libdb5.3 libdb5.3-dev libdb5.3++ libdb5.3++-dev zlib1g zlib1g-dev libssl-dev libfl-dev
