#!/bin/sh

pidfile="var/run/dreamland.pid"
corefile="core"
stopfile="var/run/shutdown.txt"

if (test -e $pidfile && (kill -0 `cat $pidfile`))
then
    exit
fi

echo $$ > $pidfile

if [ ! -r $pidfile ]
then
    exit
fi

while [ ! -r $stopfile ]
do
    index=`date "+%Y%m%d-%H%M%S"`
    logfile=var/log/$index.log

    ulimit -c unlimited    
    ulimit -c > $logfile
    ./bin/dreamland etc/dreamland.xml $* >>$logfile  2>&1

    if [ -r $corefile -a $corefile -nt $pidfile ]
    then
	mv $corefile core.$index
	ls -t core.* | (read i && read i && read i && cat) | xargs rm
    fi

    sleep 10
done   

rm -f $pidfile
